export const DEFAULT_GEMINI_MODEL = "gemini-3-flash-preview" as const;

export const RESUME_LABELS = {
  en: {
    summary: "Summary",
    experience: "Experience",
    education: "Education",
    skills: "Skills",
    certifications: "Certifications",
    languages: "Languages",
    portfolio: "Portfolio",
    matchScore: "Match Score",
    overallNotes: "Overall Notes",
    keywordsToAdd: "Keywords to Add",
    strengths: "Strengths",
    gaps: "Gaps & Improvements",
    preview: "RESUME PREVIEW",
    suggestion: "Title Suggestion",
    version: "Version",
    add: "Add",
    improvementTitle: "Add Skill",
    improvementBody:
      "Are you sure you want to add this keyword to your resume? This will increase your match score.",
    confirm: "Confirm",
    cancel: "Cancel",
  },
  pt: {
    summary: "Resumo Profissional",
    experience: "Experiência Profissional",
    education: "Formação Acadêmica",
    skills: "Competências",
    certifications: "Certificações",
    languages: "Idiomas",
    portfolio: "Portfólio",
    matchScore: "Pontuação de Match",
    overallNotes: "Notas Gerais",
    keywordsToAdd: "Palavras-chave para adicionar",
    strengths: "Pontos Fortes",
    gaps: "Lacunas e Melhorias",
    preview: "PRÉ-VISUALIZAÇÃO",
    suggestion: "Sugestão de Título",
    version: "Versão",
    add: "Adicionar",
    improvementTitle: "Adicionar Habilidade",
    improvementBody:
      "Tem certeza que deseja adicionar esta palavra-chave ao seu currículo? Isso aumentará sua pontuação de match.",
    confirm: "Confirmar",
    cancel: "Cancelar",
  },
} as const;
